name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * MON'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install IBM CLI
      run: curl -sL https://ibm.biz/idt-installer | bash

    - name: Login IBM Cloud
      env:
        IBM_EMAIL: ${{ secrets.IBM_EMAIL }}
        IBM_PWD: ${{ secrets.IBM_PWD }}
        IBM_RGN: ${{ secrets.IBM_RGN }}
      run: |
        ibmcloud login -u "$IBM_EMAIL" -p "$IBM_PWD" -r "$IBM_RGN"
    - name: Target IBM Cloud
      env:
        IBM_EMAIL: ${{ secrets.IBM_EMAIL }}
      run: |
        ibmcloud target --cf-api 'https://api.ng.bluemix.net' -o "$IBM_EMAIL" -s 'dev'  
        ibmcloud cf install
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
      run: |
        ibmcloud cf restart "$IBM_APP_NAME"
